version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_conjunta
    ports:
      - "5673:5672"       # Puerto para conexión con aplicaciones
      - "15674:15672"     # Puerto para interfaz web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
