spring:
  application:
    name: SERVICE-NOTIFICACIONES
  datasource:
    url: jdbc:postgresql://localhost:36257/db_carenotifier?user=root&password=
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: admin
server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info


