version: '3.8'

services:
  cockroach1:
    image: cockroachdb/cockroach:latest
    container_name: node1
    hostname: node1
    ports:
      - "36257:26257"  # SQL
      - "38080:8080"   # UI
    volumes:
      - cockroach1:/cockroach/cockroach-data
    command: start --insecure --store=node1 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=node1:26257,node2:26257 --advertise-addr=node1:26257

  cockroach2:
    image: cockroachdb/cockroach:latest
    container_name: node2
    hostname: node2
    ports:
      - "36258:26257"  # SQL
      - "38081:8080"   # UI
    volumes:
      - cockroach2:/cockroach/cockroach-data
    command: start --insecure --store=node2 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=node1:26257,node2:26257 --advertise-addr=node2:26257
    depends_on:
      - cockroach1

  # Inicializar el cluster (ejecutar una sola vez)
  init:
    image: cockroachdb/cockroach:latest
    container_name: init-cluster
    depends_on:
      - cockroach1
      - cockroach2
    command: init --insecure --host=node1:26257
    restart: "no"

volumes:
  cockroach1:
  cockroach2: